<?php
namespace Home\Controller;
use Think\Controller;
// 本类由系统自动生成，仅供测试用途
class VipController extends CommonController
{
	//企业会员中心
	public function comvip()
	{
		R("Common/company");
		$student=M("stu");
		//------------------------------------------------------------------------------------------
		//可能感兴趣的人才
		$jobs=$student->join("inner join job_resume on s_id=re_sid")->order("s_id desc")->limit(5)->select();
		$this->assign("jobs",$jobs);
		//------------------------------------------------------------------------------------------
		//企业基本信息
		$company=M("company");
		$where["c_id"]=session("c_id");
		$arr=$company->where($where)->find();
		//上次登陆时间显示
		$this->assign("time",session('time'));
		$this->assign("arr",$arr);
		$this->display();
	}

	//修改密码
	public function update()
	{
		$stu=M("stu");
		$company=M("Company");
		$s_id=session("s_id");
		if (!empty($_POST["submit"]))
		{
			//判断是否通过找回密码修改密码
			if(session("mi"))
			{
				//通过找回密码需改密码
				if($s_id!='')
				{
					//学生修改
					if($_POST["password"]==$_POST["password2"])
					{
						$data["s_pwd"]=$_POST["password"];
						$rr=$stu->where("s_id=".$s_id)->save($data);
						if($rr)
						{
							session(null);
							$this->success("修改成功",U("Index/index"),1);
						}
						else
						{
							$this->error("修改失败");
						}
					}
					else
					{
						$this->error("两次密码输入不正确");
					}
				}
				else
				{
					//企业修改
					if($_POST["password"]==$_POST["password2"])
					{
						$data["c_pwd"]=$_POST["password"];
						$rr=$company->where("c_id=".session('c_id'))->save($data);
						if($rr)
						{
							session(null);
							$this->success("修改成功",U("Index/index"),1);
						}
						else
						{
							$this->error("修改失败");
						}
					}
					else
					{
						$this->error("两次密码输入不正确");
					}
				}
			}
			else
			{
				//不通过找回密码
				if($s_id!='')
				{
				//学生信息修改
				$rs=$stu->find($s_id);
				if($rs["s_pwd"]==$_POST["userpwd"])
				{
					if($_POST["password"]==$_POST["password2"])
					{
						$data["s_pwd"]=$_POST["password"];
						$rr=$stu->where("s_id=".$s_id)->save($data);
						if($rr)
						{
							session(null);
							$this->success("修改成功，请重新登陆",U("Index/index"),1);
						}
						else
						{
							$this->error("修改失败");
						}
					}
					else
					{
						$this->error("两次密码输入不正确");
					}
				}
				else
				{
					$this->error("密码输入错误");
				}
			}
			else
			{
				//企业信息修改
				$rs=$company->find(session("c_id"));
				if($rs["s_pwd"]==$_POST["userpwd"])
				{
					if($_POST["password"]==$_POST["password2"])
					{
						$data["c_pwd"]=$_POST["password"];
						$rr=$company->where("c_id=".session('c_id'))->save($data);
						if($rr)
						{
							session(null);
							$this->success("修改成功，请重新登陆",U("Index/index"),1);
						}
						else
						{
							$this->error("修改失败");
						}
					}
					else
					{
						$this->error("两次密码输入不正确");
					}
				}
				else
				{
					$this->error("密码输入错误");
				}
			}
			}
			
		}
		else
		{
			if(session("s_id"))
			{
				$rs=$stu->where("s_id=".session("s_id"))->find();
			}
			else
			{
				$rs=$company->where("c_id=".session("c_id"))->find();
			}
			$this->assign("s_id",session("s_id"));
			$this->assign("rs",$rs);
			$this->assign("mi",session("mi"));
			$this->display();
		}
	}
	//密码保护
	public function protect()
	{
		$answer=M("answer");
		if(!empty($_POST["submit"]))
		{
			$data["an_qid"] =$_POST["an_qid"];
			$data["an_content"] =$_POST["an_content1"];
			if($_POST["id"])
			{
				$rs=$answer->where("an_id=".$_POST["id"])->save($data);
				if($rs)
				{
					$this->success("修改成功");
				}
				else
				{
					$this->error("修改失败");
				}
			}
			else
			{
				if(session("s_id"))
				{
					$data["an_sid"]=session("s_id");
				}
				else
				{
					$data["an_cid"]=session("c_id");
				}
				$rs=$answer->add($data);
				if($rs)
				{
					$this->success("添加成功");
				}
				else
				{
					$this->error("添加失败");
				}
			}
		}
		else
		{
			if(session("s_id"))
			{
				$id=session("s_id");
				$list=$answer->where("an_sid=".session("s_id"))->find();
			}
			else
			{
				$id=session("c_id");
				$list=$answer->where("an_cid=".session("c_id"))->find();
			}
			$question=M("question");
			$arr=$question->select();
			$this->assign("arr",$arr);
			$this->assign("list",$list);
			$this->display();
		}
	}
}